name: First Workflow

on:
  push:
    branches:
      - dev

  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: "dev"

      - name: Show hash
        run: git rev-parse HEAD

      - name: Show files
        run: ls