name: Second Workflow

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: "dev"

      - name: Create
        run: git rev-parse HEAD > "tmp-$(date +"%T").txt"

      - name: Commit changes
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m "New file" --no-verify
          git push

